import AdminInventory from '../../models/admin/InventoryModel.js';
import Wishlist from '../../models/app/WishlistModel.js';
import { createRepository } from '../../utils/repository.js';

const wishlistRepo = createRepository(Wishlist, {});

const getRolePrice = (variant, userRole) =>
  (variant?.tierPricing && variant.tierPricing[userRole]) ?? variant?.mrp ?? 0;

/**
 * POST /api/v1/wishlist/add
 * Body: { inventoryId, productId, variantIndex }
 */
export const addToWishlist = async (req, res) => {
  try {
    const userId = req.user?.id;
    const userRole = req.user?.role;
    if (!userId || !userRole) {
      return res.status(401).json({ success: false, message: 'Unauthorized' });
    }

    const { inventoryId, productId, variantIndex = 0 } = req.body || {};
    if (!inventoryId || !productId) {
      return res.status(400).json({
        success: false,
        message: 'inventoryId and productId are required',
      });
    }

    // Validate inventory and variant
    const inventory = await AdminInventory.findOne({
      _id: inventoryId,
      productId,
      isDeleted: false,
      isActive: true,
    });

    if (!inventory) {
      return res.status(404).json({
        success: false,
        message: 'Product not found in inventory',
      });
    }

    const variant = inventory.variants?.[variantIndex];
    if (!variant) {
      return res
        .status(404)
        .json({ success: false, message: 'Variant not found' });
    }

    // Load or create wishlist
    let wishlist = await Wishlist.findOne({ userId, userRole });
    if (!wishlist) {
      wishlist = new Wishlist({ userId, userRole, items: [] });
    }

    // Prevent duplicates for the same variant of a product
    const exists = wishlist.items.some(
      (it) =>
        it.inventoryId.toString() === String(inventoryId) &&
        it.productId.toString() === String(productId) &&
        it.variantIndex === Number(variantIndex),
    );
    if (exists) {
      return res.status(400).json({
        success: false,
        message: 'Variant already in wishlist',
      });
    }

    const price = getRolePrice(variant, userRole);

    // Push normalized item; _id will be generated by Mongoose
    wishlist.items.unshift({
      inventoryId,
      productId,
      variantIndex,
      name: inventory.name || '',
      image: inventory.image || '',
      price,
      originalPrice: variant.mrp ?? 0,
      quantity: variant.variantKey || '', // label like "1 kg" (not cart qty)
      category: inventory.category || '',
      inStock: !!variant.inStock,
      rating: inventory.rating ?? 0,
      addedAt: new Date(),
    });

    await wishlist.save();

    return res.status(201).json({
      success: true,
      message: 'Added to wishlist',
      wishlist,
    });
  } catch (error) {
    console.error('Error adding to wishlist:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to add to wishlist',
      error: error.message,
    });
  }
};

/**
 * DELETE /api/v1/wishlist/remove/:itemId?
 * Accepts subdocument _id via params or body.
 */
export const removeFromWishlist = async (req, res) => {
  try {
    const userId = req.user?.id;
    const userRole = req.user?.role;
    if (!userId || !userRole) {
      return res.status(401).json({ success: false, message: 'Unauthorized' });
    }

    const itemId = req.params.itemId || req.body?.itemId;
    if (!itemId) {
      return res.status(400).json({
        success: false,
        message: 'itemId is required',
      });
    }

    const wishlist = await Wishlist.findOne({ userId, userRole });
    if (!wishlist) {
      return res
        .status(404)
        .json({ success: false, message: 'Wishlist not found' });
    }

    const idx = wishlist.items.findIndex(
      (it) => String(it._id) === String(itemId),
    );
    if (idx === -1) {
      return res.status(404).json({
        success: false,
        message: 'Item not found in wishlist',
      });
    }

    wishlist.items.splice(idx, 1);
    await wishlist.save();

    return res.status(200).json({
      success: true,
      message: 'Product removed from wishlist',
      wishlist,
    });
  } catch (error) {
    console.error('Error removing from wishlist:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to remove from wishlist',
      error: error.message,
    });
  }
};

/**
 * DELETE /api/v1/wishlist/clear
 */
export const clearWishlist = async (req, res) => {
  try {
    const userId = req.user?.id;
    const userRole = req.user?.role;
    if (!userId || !userRole) {
      return res.status(401).json({ success: false, message: 'Unauthorized' });
    }

    const wishlist = await Wishlist.findOne({ userId, userRole });
    if (!wishlist) {
      return res
        .status(404)
        .json({ success: false, message: 'Wishlist not found' });
    }

    wishlist.items = [];
    await wishlist.save();

    return res.status(200).json({
      success: true,
      message: 'Wishlist cleared successfully',
      wishlist,
    });
  } catch (error) {
    console.error('Error clearing wishlist:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to clear wishlist',
      error: error.message,
    });
  }
};

/**
 * GET /api/v1/wishlist
 */
export const getWishlist = async (req, res) => {
  try {
    const { id: userId, role: userRole } = req.user || {};
    if (!userId || !userRole) {
      return res.status(401).json({ success: false, message: 'Unauthorized' });
    }

    const result = await wishlistRepo.getAll({
      filter: { userId, userRole },
      projection: { items: 1, _id: 0 },
      limit: 1,
      page: 1,
      sort: {},
    });

    if (!result.success) {
      return res.status(result.status || 500).json(result);
    }

    const wishlist = result.data[0] || { items: [] };
    return res.status(200).json({ success: true, items: wishlist.items });
  } catch (error) {
    console.error('Error fetching wishlist:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to fetch wishlist',
      error: error.message,
    });
  }
};

// import Wishlist from "../../models/app/WishlistModel.js";
// import { createRepository } from "../../utils/repository.js";

// const wishlistRepo = createRepository(Wishlist, {
//   /* any config if needed */
// });
// export const addToWishlist = async (req, res) => {
//   try {
//     const userId = req.user?.id;
//     const userRole = req.user?.role;
//     if (!userId || !userRole) {
//       return res.status(401).json({ success: false, message: 'Unauthorized' });
//     }

//       const product = req.body.product;
//       console.log("Body",req.body)
//     if (!product || !product.id) {
//       return res
//         .status(400)
//         .json({ success: false, message: 'Product data is required' });
//     }

//     // Find existing wishlist for this user and role
//     let wishlist = await Wishlist.findOne({ userId, userRole });

//     if (!wishlist) {
//       // Create new wishlist if doesn't exist
//       wishlist = new Wishlist({
//         userId,
//         userRole,
//         items: [],
//       });
//     }

//     // Check if product already exists in wishlist
// const existingIndex = wishlist.items.findIndex(
//   (item) => item.productId.toString() === product.id,
// );
//     if (existingIndex !== -1) {
//       return res
//         .status(400)
//         .json({ success: false, message: 'Product already in wishlist' });
//     }

//     // Add new product with addedAt timestamp
//     const wishlistProduct = {
//       productId: product.id,
//       name: product.name || '',
//       image: product.image || '',
//       price: product.price || 0,
//       originalPrice: product.originalPrice || 0,
//       // quantity: 1,
//       quantity: product.quantity,
//       category: product.category || '',
//       inStock: product.inStock !== undefined ? product.inStock : true,
//       rating: product.rating || 0,
//       addedAt: new Date(),
//     };

//     wishlist.items.unshift(wishlistProduct);

//     await wishlist.save();

//     return res.status(201).json({
//       success: true,
//       message: `${product.name || 'Product'} added to wishlist`,
//       wishlist,
//     });
//   } catch (error) {
//     console.error('Error adding to wishlist:', error);
//     return res
//       .status(500)
//       .json({
//         success: false,
//         message: 'Failed to add to wishlist',
//         error: error.message,
//       });
//   }
// };

// export const removeFromWishlist = async (req, res) => {
//   try {
//     const userId = req.user?.id;
//     const userRole = req.user?.role;
//     if (!userId || !userRole) {
//       return res.status(401).json({ success: false, message: 'Unauthorized' });
//     }

//     const productId = req.params.productId || req.body.productId;
//     if (!productId) {
//       return res
//         .status(400)
//         .json({ success: false, message: 'Product ID is required' });
//     }

//     const wishlist = await Wishlist.findOne({ userId, userRole });
//     if (!wishlist) {
//       return res
//         .status(404)
//         .json({ success: false, message: 'Wishlist not found' });
//     }

//     const itemIndex = wishlist.items.findIndex(
//       (item) => item.productId.toString() === productId,
//     );

//     if (itemIndex === -1) {
//       return res
//         .status(404)
//         .json({ success: false, message: 'Product not found in wishlist' });
//     }

//     wishlist.items.splice(itemIndex, 1);
//     await wishlist.save();

//     return res.status(200).json({
//       success: true,
//       message: 'Product removed from wishlist',
//       wishlist,
//     });
//   } catch (error) {
//     console.error('Error removing from wishlist:', error);
//     return res
//       .status(500)
//       .json({
//         success: false,
//         message: 'Failed to remove from wishlist',
//         error: error.message,
//       });
//   }
// };

// export const clearWishlist = async (req, res) => {
//   try {
//     const userId = req.user?.id;
//     const userRole = req.user?.role;
//     if (!userId || !userRole) {
//       return res.status(401).json({ success: false, message: 'Unauthorized' });
//     }

//     const wishlist = await Wishlist.findOne({ userId, userRole });
//     if (!wishlist) {
//       return res
//         .status(404)
//         .json({ success: false, message: 'Wishlist not found' });
//     }

//     wishlist.items = [];
//     await wishlist.save();

//     return res
//       .status(200)
//       .json({
//         success: true,
//         message: 'Wishlist cleared successfully',
//         wishlist,
//       });
//   } catch (error) {
//     console.error('Error clearing wishlist:', error);
//     return res
//       .status(500)
//       .json({
//         success: false,
//         message: 'Failed to clear wishlist',
//         error: error.message,
//       });
//   }
// };

// export const getWishlist = async (req, res) => {
//   try {
//     const { id: userId, role: userRole } = req.user || {};
//     if (!userId || !userRole)
//       return res.status(401).json({ success: false, message: 'Unauthorized' });

//     const result = await wishlistRepo.getAll({
//       filter: { userId, userRole },
//       projection: { items: 1, _id: 0 }, // just get items array
//       limit: 1,
//       page: 1,
//       sort: {},
//     });

//     if (!result.success) {
//       return res.status(result.status || 500).json(result);
//     }

//     const wishlist = result.data[0] || { items: [] };
//     return res.status(200).json({ success: true, items: wishlist.items });
//   } catch (error) {
//     console.error('Error fetching wishlist:', error);
//     return res.status(500).json({
//       success: false,
//       message: 'Failed to fetch wishlist',
//       error: error.message,
//     });
//   }
// };
